basket/urls.py
from django.urls import path

from  basket.views import basket_add, basket_remove
app_name = 'basket'

urlpatterns = [
    # path('', basket_detail, name='basket_detail'),
    path('add/<int:item_id>/', basket_add, name='basket_add'),
    path('remove/<int:item_id>/', basket_remove, name='basket_remove'),

]

requisitions/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from inventory.views import *
from requisitions.views import *
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [  
    path('requisitions_list/', requisitions_list, name = 'requisitions_list'),  
    path('create_requisition/', create_requisition, name = 'create_requisition'),
    path('edit_requisition/<int:id>/', edit_requisition, name = 'edit_requisition'), 
    path('item_details/<int:id>/', item_details, name = 'item_details'),
    path('submit_requisition/', submit_requisition, name = 'submit_requisition'),
    path('approve_requisition/<int:id>/', approve_requisition, name = 'approve_requisition'),
    path('deny_requisition/<int:id>/', deny_requisition, name = 'deny_requisition'),

    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name = 'remove_single_item_from_cart'),
    path('add_single_item_from_cart/<slug>/', add_single_item_from_cart, name = 'add_single_item_from_cart'),

    path('basket_clear/', basket_clear, name='basket_clear'),
    
    
]

sales/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from sales.views import *
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('sales_list', sales_list, name = 'sales_list'),
    path('create_sales', create_sales, name = 'create_sales'),
]

whiteelephantmis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('inventory.urls')),
    path('', include('requisitions.urls')),
    path('', include('basket.urls')),
    path('', include('sales.urls')),
    path('', include('reports.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

requisitions/models.py
from django.db import models
from django.conf import settings
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User
from django.shortcuts import reverse

from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save, pre_save
from inventory.models import *
from django.dispatch import receiver
from datetime import date, timedelta, datetime, time
from djmoney.money import Money
from common_utils.BaseModels import BaseModel
# Create your models here.

class RequestItem(BaseModel):
    request_id = models.CharField(default="", max_length=30)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    approved = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)
    approved_qty = models.IntegerField(default=0)
    requested_item_price = MoneyField(max_digits=14, decimal_places=2, default_currency='MWK', default= 0.0)
    requested_time = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return f"{self.quantity} {self.item.unit} of {self.item.item_name}"
    
    def total_approved_item_amount(self):
        amount = MoneyField()
        amount = self.approved_qty * self.requested_item_price
        return amount

    def get_item_balance(self):
        balance = self.item.quantity_at_hand - self.approved_qty
        return balance

    @property
    def amount(self):
        amount = Money(0.0, 'MWK')
        amount = self.quantity * self.requested_item_price
        return amount

request_status = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Not Approved', 'Not Approved'),
    )
    
class Requisition(BaseModel):
    def gen_code(self):
            return 'RQT%04d'%self.pk
    code = models.CharField(max_length=50, null=True, default="0000")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    items = models.ManyToManyField(RequestItem)
    status = models.CharField(max_length=15, choices=request_status, default="Pending")
    request_total_cost = MoneyField(max_digits=14, decimal_places=2, default_currency='MWK', default= 0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approved_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='Manager')
    class Meta:
         ordering = ['code']
         permissions = [("can_approve_requisition", "can approve requisition"), ("can_view_all_requisitions", "can view all requsitions")]

    @property
    def get_code(self):
        return self.gen_code
    
    def get_total_approved_request_amount(self):
        total = Money(0.0, 'MWK')
        for item in self.items.all():
            total += item.total_approved_item_amount()
        return total
    
    def __str__(self):
        return '{1} {0}'.format(self.created_at, self.user)

            

requisitions/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.views.generic import UpdateView
from django.db import models
from django_countries.fields import CountryField
# from constance.admin import ConstanceAdmin, ConstanceForm, Config
from djmoney.forms.widgets import MoneyWidget
from django.contrib.auth import authenticate, login, logout, get_user_model
from inventory.models import Item
from django.core.validators import RegexValidator

class CustomMoneyWidget(MoneyWidget):
    def format_output(self, rendered_widgets):
        return ('<div class="row form-group">'
                    '<div class="col-sm-12 ">%s</div>'
                    '<div class="col-sm-12 ">%s</div>'
                '</div>') % tuple(rendered_widgets)

class SearchForm(forms.ModelForm):
    barcode = forms.CharField(max_length=5, validators=[RegexValidator(r'^[0-9]', 'Only digit characters.')], widget = forms.TextInput(attrs={'autofocus': True, 'class': 'form-control pos_form','placeholder':'Enter Barcode','id':'barcode-input','type':'number'}) )   
    class Meta:
        model = Item
        fields = ('barcode',)

requisitions/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render,redirect, get_object_or_404
from inventory.models import *
from django.template.loader import render_to_string

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.db.models import AutoField,IntegerField,FloatField,ExpressionWrapper, F, DecimalField, Count, Sum
from djmoney.money import Money
from django.db.models.functions import TruncDay
from django.utils import timezone
from datetime import date, timedelta, datetime
from django.db.models.functions import Lower
from djmoney.models.fields import MoneyField
from .forms import SearchForm
from .models import *
from basket.basket import Basket

@login_required
def requisitions_list(request):
    if request.user.has_perm('can_view_all_requisitions'):
        requisitions = Requisition.objects.all()
        approved_requisitions = requisitions.filter(status = 'Approved')
        pending_requisitions = requisitions.filter(status = 'Pending')
        denied_requisitions = requisitions.filter(status = 'Denied')

    else:
        requisitions = Requisition.objects.filter(user=request.user)
        approved_requisitions = requisitions.filter(status = 'Approved')
        pending_requisitions = requisitions.filter(status = 'Pending')
        denied_requisitions = requisitions.filter(status = 'Denied')
    context = {
        'header':'Manage Requisitions',
        'requisitions':requisitions,
        'approved_requisitions':approved_requisitions,
        'pending_requisitions':pending_requisitions,
        'denied_requisitions':denied_requisitions,
    }
    return render(request, 'requisitions/requisitions_list.html', context)

@login_required
def create_requisition(request):
    item_search_form = SearchForm()
    items = Item.objects.all()
    item_categories = ItemCategory.objects.all()
    items = None
    item_cat_id = request.GET.get('category')
    if item_cat_id:
        items = Item.get_all_items_by_category_id(item_cat_id).filter(active=True).filter(quantity_at_hand__gt=0)
        item_count = items.count()
    else:
        items = Item.get_all_items().filter(active=True).filter(quantity_at_hand__gt=0)
        item_count = items.count()
    all_items_count = Item.objects.count()
    category = ItemCategory.objects.filter(id=item_cat_id)
    context = {
        'header':'Create Requisition',
        'item_categories':item_categories,
        'category':category,
        'items':items,
        'all_items_count':all_items_count,
        'item_count':item_count,
        'item_search_form':item_search_form,
    }
    return render(request, 'requisitions/create_requisition.html', context)

@login_required
def edit_requisition(request, id):
    item_search_form = SearchForm()
    items = Item.objects.all()
    item_categories = ItemCategory.objects.all()
    requisition = Requisition.objects.get(id = id)
    request.session['opened_requisition'] = requisition.id
    items = None
    item_cat_id = request.GET.get('category')
    if item_cat_id:
        items = Item.get_all_items_by_category_id(item_cat_id).filter(active=True).filter(quantity_at_hand__gt=0)
        item_count = items.count()
    else:
        items = Item.get_all_items().filter(active=True).filter(quantity_at_hand__gt=0)
        item_count = items.count()
    all_items_count = Item.objects.count()
    category = ItemCategory.objects.filter(id=item_cat_id)
    context = {
        'header':'Edit Requisition',
        'item_categories':item_categories,
        'category':category,
        'items':items,
        'requisition':requisition,
        'all_items_count':all_items_count,
        'item_count':item_count,
        'item_search_form':item_search_form,
    }
    return render(request, 'requisitions/edit_requisition.html', context)

@login_required
def remove_single_item_from_cart(request, slug):
    request_id =request.session['opened_requisition']
    item = get_object_or_404(Item, slug=slug)
    req_qs = Requisition.objects.filter(id = request_id)
    if req_qs.exists():
        requisition = req_qs[0]
        req_code = Requisition.objects.get(id = request_id).get_code()
        #check if the requested item is in the request
        if requisition.items.filter(item__slug = item.slug).exists():
            requested_item = RequestItem.objects.get(item=item, request_id = req_code )
            if requested_item.approved_qty > 0:
                requested_item.approved_qty -=1
                item.quantity_at_hand +=1
                requested_item.save()
                item.save()
            return redirect('/edit_requisition/'+ str(request_id))
        else:
            return redirect('/edit_requisition/'+ str(request_id))
    else:
        messages.info(request, "Item not in order")
    # return redirect('/pos/personal_order_list/'+ str(order.id))
    return redirect('/edit_requisition/'+ str(request_id))

@login_required
def add_single_item_from_cart(request, slug):
    request_id =request.session['opened_requisition']
    item = get_object_or_404(Item, slug=slug)
    req_qs = Requisition.objects.filter(id = request_id)
    if req_qs.exists():
        requisition = req_qs[0]
        req_code = Requisition.objects.get(id = request_id).get_code()
        #check if the requested item is in the request
        if requisition.items.filter(item__slug = item.slug).exists():
            requested_item = RequestItem.objects.get(item=item, request_id = req_code )
            if requested_item.item.quantity_at_hand > 0:
                requested_item.approved_qty +=1
                item.quantity_at_hand -=1
                requested_item.save()
                item.save()
            return redirect('/edit_requisition/'+ str(request_id))
        else:
            return redirect('/edit_requisition/'+ str(request_id))
    else:
        messages.info(request, "Item not in order")
    return redirect('/edit_requisition/'+ str(request_id))

#item details view
def item_details(request, id):
    item = get_object_or_404(Item, id = id)
    context = {
        'item':item,
        'title':'IMIS',
        'header': 'Item details',
    }
    return render(request, 'item_details.html', context)

#submit request
def submit_requisition(request):
    basket = Basket(request)
    if request.user.is_authenticated:
        request_total_cost =  basket.get_total_price()
        session = request.session
        req = Requisition.objects.create(user = request.user, request_total_cost = request_total_cost)
        req.code = req.get_code()
        req.save()
        req_id = req.get_code()
        for item in basket:   
            requested_item = RequestItem.objects.create(
                request_id=req_id, item =item["item"], requested_item_price=item["price"], quantity=item["qty"], approved_qty = item["qty"],
            )
            req.items.add(requested_item)
            req.save()
        messages.success(request, "Request Successfully submitted!")
        del request.session['basket']
        return redirect('requisitions_list')

def approve_requisition(request, id):
    requisition = Requisition.objects.get(id = id)
    req_id = requisition.get_code()
    requested_items = RequestItem.objects.filter(request_id = req_id)
    for requested_item in requested_items:
        item = Item.objects.get(item_name = requested_item.item)
        item.quantity_at_hand = requested_item.get_item_balance()
        item.save()
        requested_item.approved = True
        requested_item.save()
    requisition.status = "Approved"
    requisition.approved_by = request.user
    requisition.save()
    messages.success(request, "Request Successfully Approved!")
    return redirect('requisitions_list')

def deny_requisition(request, id):
    requisition = Requisition.objects.get(id = id)
    req_id = requisition.get_code()
    # requested_items = RequestItem.objects.filter(request_id = req_id)
    # for requested_item in requested_items:
    #     item = Item.objects.get(item_name = requested_item.item)
    #     item.quantity_at_hand = requested_item.get_item_balance()
    #     item.save()
    #     requested_item.approved = True
    #     requested_item.save()
    requisition.status = "Denied"
    requisition.approved_by = request.user
    requisition.save()
    messages.success(request, "Request Denied!")
    return redirect('requisitions_list')


def basket_clear(request):
    basket = Basket(request)
    print(basket)
    basket.clear()
    print(basket)
    return redirect ('create_requisition')

requisitions/templates/requisitions/create_requisition.html
{% extends 'base_inventory.html' %}


{% block content %}
<style>
  #customer_name_label{
    display: inline;
  }
</style>
<style>
  #customer_name_label{
    display: inline;
  }
  
  #item_button{
    background-color: #17a2b8 !important;
    padding: 0.15rem; 
    border-radius: 0.25rem;
  }
  .bottom-area-btns{
    min-width: 90px;
    margin: 0 1px;
    padding: 12px 0;
    height: 80px;
    bottom: 0;
    left: 0;
    position: fixed;
    right: 0;
    z-index: 1032;
    }
    

    .pagination a {
      color: black;
      float: left;
      padding: 8px 16px;
      text-decoration: none;
    }
      .pagination li.active {
      background-color: #4CAF50;
      min-height: 50px;
      min-width: 50px;
      font-size: xx-large;
      /* color: white; */
    }
    .pagination li{
      min-height: 50px;
      min-width: 50px;
      font-size: xx-large;
      /* color: white; */
    }

    .pagination a:hover:not(.active) {
      background-color: #ddd;
      min-height: 40px;
      min-width: 40px;
      font-size: xx-large;
    }
    .list-wrapper{
      min-height: 50px;
      position: relative;
    }
    #item-category-wrapper a div.active {
      background-color: #4CAF50;
    }

</style>
<div class="mb-4">
  <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-md-center justify-content-start border-bottom mb-2" style="font-size: x-large;">
    <a class="nav-item" href="#"><b>{{request.get_code}}</b></a>  
    <div class="navbar-collapse collapse justify-content-between align-items-center">
        

        <ul class="navbar-nav mx-auto text-md-center text-left"> 
           
        </ul>
      
        <ul class="nav navbar-nav flex-row justify-content-md-center justify-content-start flex-nowrap"> 
            <li class="nav-item">
              <form class="q" method="POST">
                  <div class="input-group searchform" name ="q">
                      {% csrf_token %}
                      {{item_search_form.barcode}}
                      <div class="input-group-append">
                          <button type="submit" class="btn btn-secondary show-form" style="width: 90px;"><i class="fa fa-barcode"></i></button>
                      </div>
                  </div>
              </form>
          </li>
        </ul> 
    </div>
  </nav>

  <!--ROW-->
  <div class="row mb-4">
    {% if basket %}
    {%else%}
  <style>
    #cart_section{
      display: none;
    }
    #other_payments{
      display: none;
    }
    .cart_button{
      width: 150px;
    }
  </style>
    {% endif %}

  {% if basket|length == 0 %}
    <!--CART ITEMS-->
    <div class="col-md-6" >
      <div class="card ml-2" >
          <div class="card-body text-center">

            <a class="btn btn-default disabled" style="width: 100px; height: 100px; border-style: dotted; border-radius: 2ex; border-width: 3px;" ></a> <br>

            <strong> Request is Empty!</strong> <br>
              Add Items to the request
          </div>
                
      </div>

    </div>
    <!--END CART ITEMS-->
  {% else %}
    <!--CART ITEMS-->
    <div class="col-md-6" >
        <div class="card" id="cart_section">
            <div class="card-header">
                <h3 class="card-title">Requested Items</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table m-0">
                      <thead>
                      <tr>
                        <th>Item</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-right">Cost</th>
                        <th class="text-right">Total</th>
                        <th></th>
                      </tr>
                      </thead>
                      <tbody>
                    {% for ordered_item in basket %}
                      <tr>
                        <td>{{ordered_item.item}}</td>
                        <td class="text-center"></a>{{ordered_item.qty}}</td>
                        <td class="text-right">{{ordered_item.price}}</td>
                        <td class="text-right">{{ordered_item.total_price}}</td>
                        <td class="text-center"> <a href="{% url 'basket:basket_remove' ordered_item.item.id %}"> <button class="btn btn-outline-info"><i class="fas fa-times"></i></button></td>
                        </tr>
                      
                      {% endfor %}
                      {% if basket|length > 0 %}
                      <tr>
                        <td colspan="2"></td>
                        <td colspan="1" class="text-right" style="background-color:#343a40; font-size: 100%; font-family: monospace; color: chartreuse;" class="col-md-6"><h4>TOTAL</h4></td>
                        <td colspan="1" class="text-right" style="background-color:#343a40; font-size: 100%; font-family: monospace; color: chartreuse;" class="col-md-6"> <h4>{{basket.get_subtotal_price}}</h4></td>
                        <td colspan="1" class="text-right" style="background-color:#343a40; font-size: 100%; font-family: monospace; color: chartreuse;" class="col-md-6"></td>
                      </tr>
                      {% endif %}
                      </tbody>
                    </table>
                </div>
                <div class="col-md-12" style="float: right;">
                    <div class="mt-2">
                      <button class="btn btn-success posoption_button mr-2 ml-2 mt-2" data-toggle="modal" data-target="#confirm_submit_requisition_modal" role="button" > Submit</button>
                      <button class="btn btn-warning posoption_button mr-2 ml-2 mt-2" data-toggle="modal" data-target="#confirm_cancel_requisition_modal" role="button" > Cancel</button>
                    </div>
                  
                </div>

            </div>    
        </div> 
        
    </div>

    <!--END CART ITEMS-->
  {% endif %}

      <!--ITEMS TABLE-->
      <div class="col-6">
        <div class="card card-info card-outline card-outline-tabs">
          <div class="row">
            <div class="col-3 ml-2" id="item-category-wrapper">
                <a  href="{% url 'create_requisition'%}">
                  <div class="info-box active">
                      <div>
                          <span class="info-box-text"> <strong>All</strong></span>
    
                      </div>
                  <!-- /.info-box-content -->
                  </div>
                </a> 
              {% for item_category in item_categories %}
                  <!-- /.info-box -->    
                  <a  href="/create_requisition?category={{item_category.id}}">
                      <div class="info-box text-center bg-secondary" >
                          <div>
                              <span class="info-box-text"> <strong>{{item_category.category_name}}</strong></span>
                          </div>
                      <!-- /.info-box-content -->
                      </div>
                  </a> 
              {% endfor %}
            </div>
            <div class="col-8 row" id="list-wrapper">
              {% for item in items %}
                <div class="col-md-4 mb-2 px-1 list-item">
                  <a href="{% url 'item_details' item.id %}">
                  <div  id="item_button" class="item-box mt-0 text-center" data-toggle="modal" data-target="#productBox">
                      <div class="txt-box">
                          <span class="text-dark"> <strong>{{item.selling_price}}</strong> </span>
                      </div>
                      <div class="img-box">
                          <img src = "{{item.image.url}}"class="img-fluid" alt="">
                      </div>
                      <div class="txt-box item-name">
                          <span class="text-dark"><strong>{{item.item_name}}</strong></span>
                      </div>
                  </div>
                </a>
                </div>
              {% endfor %}
              <nav aria-label="Page navigation">
                <ul class="pagination">
                  <li id="previous-page">
                    <a href="javascript:void(0)" aria-label="Previous" >
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
      <!--END ITEMS TABLE-->
  <!--END ROW-->
  </div>
</div>

<!-- confirm cancel request modal -->
<div class="modal fade" id="confirm_cancel_requisition_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning">
        <h4 class="modal-title">Confirm Canceling the Requisition</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to cancel the requisition?</p>
      </div>
      <div class="modal-footer justify-content-between">
        <a href="{% url 'basket_clear' %}"><button type="button" class="btn btn-default">Yes</button> </a>
        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- confirm cancel request modal -->

<!-- confirm submit request modal -->
<div class="modal fade" id="confirm_submit_requisition_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-success">
        <h4 class="modal-title">Confirm submitting the Requisition</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to submit the requisition?</p>
      </div>
      <div class="modal-footer justify-content-between">
        <a href="{% url 'submit_requisition' %}"><button type="button" class="btn btn-success">Yes</button> </a>
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- confirm submit request modal -->
{% endblock %}